### ISSUE TITLE
Magento версия 2.0.2

### ISSUE THREAD

**Issue by viskas** [bxn5/magegain-novaposhta#1]
Нет связи между таблицами novaposhta_city и novaposhta_warhouse, так как в столбце city_id везде нули.
В чем может быть проблема?

**Comment by bxn5** [comment]
Нули в смысле есть строки но все значения null ? Вы синхронизацию в админке делали? Что отображается в админке в списке городов?

**Comment by viskas** [comment]
Да делали синхронизацию, и в столбец city_id пишутся 0 
![photo_2017-01-19_16-46-43](https://cloud.githubusercontent.com/assets/20912878/22111135/e8d49c6e-de66-11e6-98c3-f54f82f5453d.jpg)

**Comment by bxn5** [comment]
а скриншот таблички с городами можно?

**Comment by viskas** [comment]
![photo_2017-01-19_17-02-33](https://cloud.githubusercontent.com/assets/20912878/22111745/1b7a91c6-de69-11e6-9e08-f9cfd3eb4ce1.jpg)
![photo_2017-01-19_16-46-43](https://cloud.githubusercontent.com/assets/20912878/22111744/1b707be6-de69-11e6-8a44-883e2e2c24ba.jpg)

**Comment by bxn5** [comment]
Исправил, спасибо
обновите файлик Magegain/Novaposhta/Controller/Adminhtml/Warhouse/Sync.php очистите таблицы и выполните синхронизацию снова

**Comment by viskas** [comment]
Исправил, не помогло. После синхронизации вот такой результат:
![photo_2017-01-19_17-18-57](https://cloud.githubusercontent.com/assets/20912878/22112398/6a27da2a-de6b-11e6-9406-bcfbd2aad450.jpg)

**Comment by bxn5** [comment]
таблицу чистили?
еще раз bin/magento setup:upgrade в консоле сделайте, скорее всего кеш остался - и убедитесь что применились изменения этого комита https://github.com/bxn5/magegain-novaposhta/commit/a6253042b40c1c34b448346c0a35840712c2af8a

**Comment by viskas** [comment]
Таблицу чистил, кэш чистил через админку и вручную. 
Изменения комита применились.
В консоле php -f bin/magento setup:upgrade делал.
После этих операций ничего не изменилось, так и пишутся "0".

**Comment by bxn5** [comment]
должно работать, а маджента у вас в режиме разрабокти работает ?  
 есть возможность скинуть вашу мадженту что бы я у себя развернул?

**Comment by viskas** [comment]
Возможно проще будет по тимвиверу решить этот вопрос?
Или общаться в скайпе, телеграмме?

**Comment by bxn5** [comment]
нет, я так сам посмотрю в чем дело, когда будет время

**Comment by viskas** [comment]
Почту можете дать?

**Comment by bxn5** [comment]
можно залить на http://fex.net/

**Comment by viskas** [comment]
http://fex.net/#!756573475705

**Comment by bxn5** [comment]
у меня все заработало, вы не применили мой коммит 
и еще не включили режим разработчика в .htaccess разкоментировать SetEnv MAGE_MODE developer

**Comment by bxn5** [comment]
нет
не заработал на фронт-енде, и не заработает
получается на версиях ниже 2.1 работать  модуль к сожалению не будет, подробнее в readme
