### ISSUE TITLE
Не работает в версии 2.2.1

### ISSUE THREAD

**Issue by sarootua** [bxn5/magegain-novaposhta#12]
Модуль не работает в версии 2.2.1 - при попытке войтив города/склады для синхронизации - вылетает с ошибками

**Comment by bxn5** [comment]
c какими?

**Comment by sarootua** [comment]
В самом меню админки. При нажатии на ссылку. М2.2.1 се

**Comment by bxn5** [comment]
Я имею в виду какие конкретно ошибки вылетают?
а еще лучше оформить ишу по этому шаблону https://github.com/magento/magento2/blob/2.2-develop/ISSUE_TEMPLATE.md

**Comment by sarootua** [comment]
![error_np_screen](https://user-images.githubusercontent.com/20066738/32738118-a173ab52-c8a4-11e7-9129-a14468d99651.jpg)
[error_NP.txt](https://github.com/bxn5/magegain-novaposhta/files/1467695/error_NP.txt)


![error_np_screen](https://user-images.githubusercontent.com/20066738/32738104-9829bffa-c8a4-11e7-9225-95d0b5de5ada.jpg)
Preconditions
- Magento 2.2.1/2 
- php-fm + nginx и nginx + apache
- Ubuntu 16.10
- mysql 5,7
Steps to reproduce
- Установлена чистая мадженто с/без демо данных (шаблон лума по умолчанию)
- скопировал модуль НП в app/code
- запустил команды (все для полного контроля)
1) rm -rf var/cache/* var/composer_home/cache/* var/di/* var/generation/* var/log/* var/page_cache/* var/tmp/* var/view_preprocessed/* var/report/* session/* pub/static/* generated/code/* generated/metadata/* pub/static/*
2) chmod u+x bin/magento
3) php bin/magento setup:upgrade
4) php bin/magento setup:di:compile
5) php bin/magento setup:static-content:deploy -f
6) php bin/magento cache:flush
7) php bin/magento indexer:reindex
8) php bin/magento cache:clean
9) chown $name_suite:$name_suite -R $path_suite
10) chmod 777 -R ./*
- установлен модуль новой почты
- В админке прописал ключ НП и без прописывания ключа НП
- захожу в меню Sales->Нова пошта міста (ошибка см скрин)
Expected result
- синхронизировать города/склады
- использовать модуль доставки товаров службой НП
Actual result
скрин 
http://prntscr.com/h9ykcu

**Comment by sarootua** [comment]
эту ошибку победил (убрал блок аргументов в xml - склады и города синхронизировал - все ок.
но при оформлении заказа не дает выбрать отделение НП - вот скрин
https://prnt.sc/h9yyrn

**Comment by bxn5** [comment]
сложно сказать, я потестировал на 2.2.1 и ошибок вообще не выявил

**Comment by sarootua** [comment]
Может по тим вюверу или по скайпу пробежимся? буду очень благодарен
скайп sarootua

**Comment by sarootua** [comment]
Вроди заработало, но в заказ не подтягивается отделение новой почты, которое я выбрал при оформлении заказа. так и должно быть или где посмотреть в заказе номер отделения?

**Comment by bxn5** [comment]
#14

**Comment by rsulym** [comment]
в 2.2.1 прекрасно работает, а в 2.2.2 нет, не обновляет блок shipping methods. сейчас сделаю подробное описание.

**Comment by gamul** [comment]
M2.2.2
В родном чекауте выглядит вот так: https://www.screencast.com/t/ehKHqxFf6 - нет выбора отделений. При переключении на адресную доставку - выглядит так же.

В onestepcheckout (Aheadworks OneStepCheckout) поле "Отделение новой почты" не отображается. После выбора любого из способов доставки (отделение или адрес) вылазят ошибки:
1. Ошибка 500 для /rest/default/V1/carts/mine/shipping-information https://www.screencast.com/t/FYreWaTOm5a
2. В var\report\api\

`"Fatal Error: 'Uncaught Error: Call to a member function getCarrierDepartment() on null in D:\\Winginx\\home\\mysite.local\\public_html\\app\\code\\Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin.php:19\nStack trace:\n#0 D:\\Winginx\\home\\mysite.local\\public_html\\vendor\\magento\\framework\\Interception\\Interceptor.php(121): Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin->beforeSaveAddressInformation(Object(Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor), 17, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#1 D:\\Winginx\\home\\mysite.local\\public_html\\vendor\\magento\\framework\\Interception\\Interceptor.php(153): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(17, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#2 D:\\Winginx\\home\\mysite.local\\public_html\\generated\\code\\Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor.php(26): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)\n#3 [i' in 'D:\\Winginx\\home\\mysite.local\\public_html\\app\\code\\Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin.php' on line 19"`

@bxn5 , можно с вами связаться напрямую? Почта, скайп, телефон? Напишите, пожалуйста, sergei.gamul@gmail.com
