### ISSUE TITLE
При синхронизации складов ошибка

### ISSUE THREAD

**Issue by marina58** [bxn5/magegain-novaposhta#13]
При первой синхронизации складов ошибка
Parse error: syntax error, unexpected '?' in /app/code/Magegain/Novaposhta/Controller/Adminhtml/Warhouse/Sync.php on line 124

**Comment by marina58** [comment]
Я не сильна в PXP, закоментарила // $citiesRefArray[$warhouseItemApi->CityRef] ?? false;
написала $cityID = true;
и синхронизация прошла успешно. 
Но есть новые ньюансы.
Нова пошта появилась в бекэнде, но я никге не нашла ее в фронтенде.
Нужно у Новой почты брать виджеты?

**Comment by bxn5** [comment]
Версия PHP должна быть 7 и выше
