### ISSUE TITLE
does not show NP shipping method on M2.2.2 frontend

### ISSUE THREAD

**Issue by rsulym** [bxn5/magegain-novaposhta#15]
Preconditions

Magento 2.2.2
php-fm + nginx
Debian 9
mysql 7
Steps to reproduce
Установлена чистая мадженто без демо данных (шаблон лума по умолчанию, custom theme)
скопировал модуль НП в app/code
запустил команды (все для полного контроля)
rm -rf var/cache/* var/composer_home/cache/* var/di/* var/generation/* var/log/* var/page_cache/* var/tmp/* var/view_preprocessed/* var/report/* session/* pub/static/* generated/code/* generated/metadata/* pub/static/*
chmod u+x bin/magento
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento cache:flush
php bin/magento indexer:reindex
php bin/magento cache:clean
chown $name_suite:$name_suite -R $path_suite
chmod 777 -R ./*
установлен модуль новой почты
В админке прописал ключ НП 
города и отделения синхронизировались ОК
создан новый товар

Expected result
get shipping calculated

Actual result

only fixed shipping method appeared, while shipping method block reloaded
https://prnt.sc/hvlu6x

**Comment by negative-one1** [comment]
Have exactly the same problem.

Magento 2.1.7 
CentOS 7.3
PHP 7.0
mySQL5.6
Appache Server

**Comment by negative-one1** [comment]
**Запустив.** 
Не правильно розумів, як в результаті спосіб доставки має працювати.

в validation rules прописано, що "місто" є обов'язковим полем.
\Novaposhta\view\frontend\web\js\model\shipping-rates-validation-rules.js
http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_carrier.html


1. На сторінці Checkout почав вводити дані в графу "Місто" - з'явилась можливість вибрати місто зі списку
2. Після того, як вибрав місто зі списку, в таблиці способів доставки з'являється 2 способи від НП.

**Comment by rsulym** [comment]
так не працює ж на 2.2.2 (((
