### ISSUE TITLE
Много орфографических ошибок.

### ISSUE THREAD

**Issue by andrewbess** [bxn5/magegain-novaposhta#18]
Сорри конечно, но такие шибки как warhouse (я так понимаю военный дом) вместо warehouse.
Тексты требуемые для перевода сразу на русском в файле Magegain/Novaposhta/Model/Carrier/Newposhta.php (тут тоже кажется что должно быть не Newposhta, а Novaposhta):
152 строка $carrierData = ['carrierTitle' => __('Новая почта'), 'methodCode' => 'newposhtahome', 'methodTitle' => __('Доставка на дом')];
и т.д.

Я думаю, что желательно привести это к нормальному виду.

**Comment by bxn5** [comment]
@andrewbess полностью с вами согласен, это open source, если желательно привести к нормальному виду - возьмите и приведите
