### ISSUE TITLE
На ver. 2.1.3 не выводит на front

### ISSUE THREAD

**Issue by viskas** [bxn5/magegain-novaposhta#2]
Обновил версию с 2.0.2 до 2.1.3 и не выводит на front-end. Что может быть? Сможете посмотреть?
Ключ для fex 847072331598

**Comment by bxn5** [comment]
в консоле браузера есть ошибки?

**Comment by viskas** [comment]
да

**Comment by bxn5** [comment]
ну эта ошибка скорее всего не имеет отношения к моему модулю

**Comment by viskas** [comment]
Я не понимаю почему он не выводится на front. Вы можете помочь?

**Comment by bxn5** [comment]
я смогу помочь если вы найдете конкретную ошибку моего модуля

**Comment by viskas** [comment]
При вводе данных о доставке, город и тд. должно подтягивать из бд отделения и тд? Есть где то пример где полностью рабочий модуль, да бы посмотреть как он работает?
![default](https://cloud.githubusercontent.com/assets/20912878/22404256/b809e4aa-e635-11e6-8466-6d457a469a9c.JPG)

**Comment by bxn5** [comment]
в readme есть обьяснение по этому поводу - если отделений больше 50 в городе то они трансформируются в один вот такой как на скриншоте. Это будет исправлено в будущих версиях, пока еще не придумал хорошего решения  как лучше это сделать в рамках мадженты.

**Comment by viskas** [comment]
Понял. Спасибо. Тобишь получается идет просчет сразу на все отделения?

**Comment by bxn5** [comment]
цены доставки?
Она расчитывается из веса товаров и  города отправителя и получателя т.е конкретное отделение не влияет на стоимость доставки

**Comment by viskas** [comment]
А почему тогда доставка дороже чем сам товар? Если вес товара не указан. Если указан то меньше килограмма.

**Comment by bxn5** [comment]
а в настройках доставки наверное у вас  килограммы стоят потому такая большая цена

**Comment by viskas** [comment]
В настройках самой системы нет возможности выбора грамм. или кг или lbs. И значение кг в системе kgs

**Comment by bxn5** [comment]
есть настройка в настройке доставки

**Comment by viskas** [comment]
Извините за беспокойство, как убрать расчет стоимости доставки и выводить все отделения в выбранном городе?

**Comment by bxn5** [comment]
ну не советовал бы, в Киве их наверное штук 200 будет, страница у половины пользователей будет виснуть или очень долго грузится
ну в целом в моделе доставки это все можно поменять Model/Carrier
