### ISSUE TITLE
2.2.2 Синхронизация первая

### ISSUE THREAD

**Issue by bigshusha** [bxn5/magegain-novaposhta#21]
При попытке в админке зайти обновить выпадает ошибка
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /var/www/html/app/code/Magegain/Novaposhta/view/adminhtml/ui_component/city_listing.xml:
Element 'argument': This element is not expected.
Line: 54`
то же самое и со складами
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /var/www/html/app/code/Magegain/Novaposhta/view/adminhtml/ui_component/warhouse_listing.xml:
Element 'argument': This element is not expected.
Line: 54`
Коментирование строк с 54 по 59 в city_listing.xml и warhouse_listing.xml, вот этого кода
`<argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="template" xsi:type="string">ui/grid/toolbar</item>
                <item name="stickyTmpl" xsi:type="string">ui/grid/sticky/toolbar</item>
            </item>
        </argument>
`
ну и синхронизация открывается и работает...

**Comment by bigshusha** [comment]
Но к сожалению не работает в фронтенде.
@bxn5  будет ли суппорт 2.2.2?

**Comment by bxn5** [comment]
@bigshusha будет
планирую на выходных начать

**Comment by bigshusha** [comment]
Готов принять посильное и всестороннее участие. Если необходима какая помощь от не очень програмиста, я готов, скайп, телега, тестирование... А вы уроков по програмированию модулей не даете (я понял что вы из Киева)?

**Comment by bxn5** [comment]
админку исправил,  с фронтом сложнее - баг в коре
