### ISSUE TITLE
2.2.2 Во фронте не хочет отображаться.

### ISSUE THREAD

**Issue by dukir** [bxn5/magegain-novaposhta#22]
Являюсь новичком, что только не пробовал - не появляется во фронте. В чем проблема?
Автор, как можно с тобой связаться? - Несколько вопросов по модулю есть.
P.S. Если не в напряг.

**Comment by bxn5** [comment]
похоже проблема та же https://github.com/magento/magento2/issues/3789

**Comment by bxn5** [comment]
#20

**Comment by shmVan** [comment]
Здравствуйте @bxn5 . Какие именно файлы обновили? В репозитории вижу старые датнные 23-дня в основном.
