### ISSUE TITLE
Не отображается отделение при заказе после чекаута через модуль Новой Почты. 

### ISSUE THREAD

**Issue by alfared** [bxn5/magegain-novaposhta#24]
Добрый день.Скажите пожалуйста как можно исправить эту ошибку. Не отображается отделение при заказе после чекаута.
<img width="780" alt="screen shot 2018-07-16 at 09 10 34" src="https://user-images.githubusercontent.com/2605754/42744865-277a17f6-88d8-11e8-89f5-6c75a0b9a1cf.png">

**Comment by bxn5** [comment]
#14

**Comment by makxxi** [comment]
Привіт. А можете підказати в якому напрямку копати для виводу відділення, у версі 1.0.2 не виводиться. Тут модуль правити потрібно?

**Comment by alfared** [comment]
Я додав до коментарів номер віділення через модуль Bold_OrderComment в списку замовлення.
Плюс для кожного товару потрібно вказати вагу та розміри на сторінці товару в адмінці.
