### ISSUE TITLE
Відсутні пункти меню синхронізації міст та складів

### ISSUE THREAD

**Issue by MrSena** [bxn5/magegain-novaposhta#3]
"После этого идем в Sales там будут 2 пункта меню: синхронизация городов и складов"
![2017-02-07-16 00 05-8201](https://cloud.githubusercontent.com/assets/5140009/22694192/e14eb85c-ed4e-11e6-8ad8-240e6b73cf80.png)

**Comment by MrSena** [comment]
Зрозумів свою помилку. Не в тому Sales шукав.

**Comment by bxn5** [comment]
если вам не сложно прикрепите скриншот где они находятся, вдруг кто еще столкнется

**Comment by MrSena** [comment]
![2017-02-07-16 14 44-f689](https://cloud.githubusercontent.com/assets/5140009/22694614/99503e48-ed50-11e6-9400-e06d654ffed8.png)

**Comment by bxn5** [comment]
дякую
