### ISSUE TITLE
Навіщо потрібна синхронізація відділень, якщо вибору відділення ніде не передбачено?

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [bxn5/magegain-novaposhta#4]
Пройшовши процедуру оформлення замовлення обираю метод доставки "Доставка до отделения(номер укажите в коментарии к заказу)". Явно поле коментаря замовлення в стандартній Luma відсутнє, тому звичайний користувач взагалі його не вкаже. Окрім того не ясно навіщо взагалі в такій ситуації синхронізація складів.

**Comment by bxn5** [comment]
в readme "Если у выбранного города больше 50 отделений то выводится 1 пункт доставки, и клиент должен будет написать номер отделения в комментариях или сообщить менеджеру (будет исправлено в будущих версиях)"

если в городе меньше 50 отделений - выводится список с номерами отделений

**Comment by MrSena** [comment]
Ідею зрозумів. Але такий спосіб реалізації доволі складний для користувача. Якщо глянути на статистику місцезнаходження більшості покупців в інтернет магазинах, то вони як раз знаходяться в містах з 50+ відділень.
Ви приймаєте індивідуальні замовлення на доопрацювання модуля?

**Comment by bxn5** [comment]
ну выводить как отдельные методы больше ста отделений просто вешает страницу заказа юзера или ооочень долго грузится и размывает другие варианты доставки (я вначале так и сделал)

пока что есть идея добавлять динамический выпадающий список после выбора города, но это может сбивать с толку если покупатель не хочет использовать новую почту 

опишите как вы видите механизм выбора

**Comment by MrSena** [comment]
Концепція стандартного чекаута в Magento обмежує прості варіанти реалізації. 
Показувати перелік складів потрібно лише якщо обрано відповідний метод доставки (НП, склад) . Тому перелік потрібно показувати як додаткову опцію метода доставки. Але тоді це ускладнює зберігання обраного складу в адресі доставки.
Тут же важливо ще лишити функціонал для зареєстрованого користувача із збереженими адресами...

**Comment by MrSena** [comment]
Якщо розвивати Ваш спосіб реалізації, то всі методи доставки Нової пошту (по суті всі доступні склади) потрібно об`єднати в один dropdown (або autocomplete) і емулювати вибір radiobutton.
Але це потрібно сильно поприсідати, як я розумію...

**Comment by bxn5** [comment]
тоже думал об этом, но это самый сложный вариант, под какую то определенную реализацию может еще это можно сделать, но это же еще надо учитывать, что модуль может использоваться и не в стандартных чекаутах

**Comment by MrSena** [comment]
У Вашої реалізації є один суттєвий недолік - в адресі не зберігається інформація про обраний склад НП. Відповідно, постійний покупець кожного разу мусить вводити номер відділення НП.

**Comment by yumicom** [comment]
В таком виде как сейчас есть модуль, его без переделки не будут использовать - визуально очень страшно смотрится длинная простыня отделений, нужен аккуратный дропдаун. Доработайте, и люди к вам потянутся )) в том числе и платно

**Comment by bxn5** [comment]
@Serhiy-Nazarov @yumicom доделал, должно появляться поле с автокомплитом выбора отделения,  после выбора метода доставки
