### ISSUE TITLE
Розширити перелік міст відправника

### ISSUE THREAD

**Issue by ivan-krechko** [bxn5/magegain-novaposhta#8]
Усім привіт! )

Чому такий малий вибір?..

З повагою,
Іван

**Comment by bxn5** [comment]
Добрий день) робiть pull request, додайте якi необхiдно, це не важко,
 ось файл
https://github.com/bxn5/magegain-novaposhta/blob/master/Magegain/Novaposhta/Model/Config/Source/CityList.php
