### ISSUE TITLE
Json inside json

### ISSUE THREAD

**Issue by VitaliyBoyko** [bxn5/magegain-novaposhta#9]
magegain-novaposhta/Magegain/Novaposhta/Controller/Ajax/Cities.php

return $this->resultJsonFactory->create()->setData(json_encode($to_json));

Навіщо json завертати в json? 
resultJsonFactory і без json_encode відправляє json.

**Comment by bxn5** [comment]
пишите, тестируйте, делайте пул реквест,   это open source
